# GCC compiler
CC=g++

# compilation flags (none)
LDFLAGS=

# source file
SOURCE=./stats_serial.cpp

# binary name
EXEC=stats_serial.exe

all:
	$(CC) $(LDFLAGS) $(SOURCE) -o $(EXEC)
	@echo -e "----- COMPILATION DONE -----"

clean:
	rm -r $(EXEC)

