# Fortran GCC compiler
CC=gcc

# compilation flags (none)
LDFLAGS=

# source file
SOURCE=./saxpy_serial.c

# binary name
EXEC=a.out

all:
	$(CC) $(FDFLAGS) $(SOURCE) -o $(EXEC)
	@echo -e "----- COMPILATION DONE -----"


clean:
	rm -r $(EXEC)

